# Generated by Django 4.2.30 on 2026-05-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='official_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Resmi Plaka (Varsa)'),
        ),
    ]
