# Generated by Django 4.2.30 on 2026-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_official_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
