# Generated by Django 4.2.30 on 2026-05-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_vehicle_model_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='chassis_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='engine_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='transmission_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
    ]
